config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  get 'home/about', to: 'homes#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end


  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'searchs#search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #ファロー・フォロワー機能のアソシエーション
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  #ここまで
  #ファロー・フォロワー機能のメソッド
  def follow(user_id)
    unless self.id == user_id.to_i
      self.relationships.create(followed_id: user_id) #self = current_userだけに限定しないため・書く必要はないが書かない場合も実際は隠れている
    end
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  #ここまで


  attachment :profile_image

  validates :name, length: {minimum: 2, maximum: 20 }, uniqueness: true

  validates :introduction, length: {maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def index
    @book = Book.new
   
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:success] = "You have updated user successfully."
    else
      flash[:danger] = "プロフィールの更新に失敗しました"
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userssearch.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>name</th>
          <th>introduction</th>
        </tr>
      </thead>
      <tbody id="user">
      <% users.each do |users| %>
        <tr>
          <td>
            <%= attachment_image_tag users, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          </td>
          <td>
            <%= link_to user_path(users) do %>
              <%= users.name %><br>
            <% end %>
          </td>
          <td>
            <%= users.introduction %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>User info</h1>
        <% if @user.errors.any? %>
          <%= @user.errors.count %>件のエラーが発生しました
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>
  　　    　<div class="form-group">
            <label for="user_name">Name</label></br>
            <%= f.text_field :name, autofocus: true, id:"inputtitle", placeholder:"名前" %>
          </div>
          <div>
            <%#= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
            <label for="inputImage">Image</label></br>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          <div class="form-group">
            <label for="user_Introduction">Introduction</label></br>
            <%= f.text_area :introduction, autofocus: true, id:"inputbody", placeholder:"紹介" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-sm btn-secondary destroy_user_id" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
  　<%= render 'books/user', user: current_user, book: @book %>
  　</div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr></tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
        <tr>
          <td>
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
            フォロー数：<%= user.followings.count %>
          </td>
          <td>
            フォロワー数：<%= user.followers.count %>
          </td>
          <td>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          </td>
          <td>
            <%= link_to "Show", user_path(user.id) %>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
  　<%= render 'books/user', user: @user, book: @book %>
  　</div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <!--<th colspan="3"></th>-->
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
            <% end %>
            <%#= image_tag('sample-author1.jpg') %>
          </td>
          <td>
            <%= link_to book.title, book_path(book.id) %>
          </td>
          <td>
            <%= book.body %>
          </td>
          <td>
            <% if current_user.following?(@user) %>
              <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
            <% end %>
          </td>
          <td>
            <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>