config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  get 'home/about', to: 'homes#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end


  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'searchs#search'

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = @book.user
    if @book.save
      redirect_to book_path(@book.id)
      flash[:success] = "You have created book successfully."
    else
      @books = Book.all
      flash.now[:danger] = "新規投稿に失敗しました"
      render :index
    end
  end

  def index
    # @book = Book.find(params[:id])
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:success] = "You have updated book successfully."
    else
      flash.now[:danger] = "errors prohibited this obj from being saved:"
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to  books_path
    else
      @book.destroy
      redirect_to books_path
    end

  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_bookssearch.html.erb
      <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
     <tbody id="book">
      <% books.each do |books| %>
        <tr>
          <td>
            <%= attachment_image_tag books.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          </td>
          <td>
            <%= link_to book_path(books) do %>
              <%= books.title %>
            <% end %>
          </td>
          <td>
           <%= books.body %>
         </td>
        </tr>
      <% end %>
      </tbody>
      </table>

app/views/books/_user.html.erb
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <!--<img class="attachment user profile_image fallback" src="/assets/no_image-72379a4da21cb04a58337cf92d85bc39f8d534cbc78254c2085acaca82236bfa.jpg">-->
      <table class="table">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= user.introduction %></td>
          </tr>
          <tr>
            <td>follows</td>
            <td><%= link_to user.followings.count, user_followings_path(user) %></td>
          </tr>
          <tr>
            <td>follwers</td>
            <td><%= link_to user.followers.count, user_followers_path(user) %></td>
          </tr>
        </tbody>
      </table>

      <% if controller.action_name == 'show' %>
        <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), class: "btn btn-sm btn-info", method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), class: "btn btn-sm btn-success", method: :post %>
        <% end %>
      <% end %>

      <%= link_to "",edit_user_path(user.id), class: :"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_33315" %>

      <h2>New book</h2>
      <!-- form_with部分 -->
      <%= form_with model:book, url:'/books', local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>件のエラーが発生しました
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>

        <%= form_with model:@book, local:true do |f| %>
  　　    　<div class="form-group">
            <label for="book_title">Title</label></br>
            <%= f.text_field :title, autofocus: true, id:"inputtitle", placeholder:"タイトル" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label></br>
            <%= f.text_area :body, autofocus: true, id:"inputbody", placeholder:"本文" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class="container">
    <div id="error_explanation">
      <h3>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>件のエラーが発生しました
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      </h3>
    </div>
    <div class="row">
      <div class="col-md-3">
      <%= render 'books/user', user: @user, book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
              <!--<a class="book_id" href="/books/id"></a>-->
            </td>
            <td>
              <%= book.body %>
            </td>
            <td id="favorite_buttons_<%= book.id %>">
              <%= render 'favorites/favorites', book: book %>
            </td>
            <td>
              <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
            </td>
          </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/user', book: @new_book, user: @book.user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
        <tr>
          <td>
            <%= link_to user_path(@book.user.id) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
              <br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to @book.title, book_path(@book.id) %>
            <!--<a class="book_id" href="/books/id"><%#= book.title %></a>-->
          </td>
          <td>
            <%= @book.body %>
          </td>
          <td>
            <% if @book.user_id == current_user.id %>
              <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success destroy_book_id" %>
            <% end %>
          </td>
          <td>
            <% if @book.user_id == current_user.id %>
              <%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger destroy_book_id", method: :delete %>
            <% end %>
          </td>
          <td id="favorite_buttons_<%= @book.id %>">
            <%= render 'favorites/favorites', book: @book %>
          </td>
          <td>
            コメント件数: <%= @book.book_comments.count %>
          </td>
        </tr>
        </tbody>
      </table>
      <div id="comments_buttons_<%= @book.id %>">
      <%= render 'book_comments/comments', book: @book %>
      </div>
      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>
    </div>
  </div>
</div>