config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  get 'home/about', to: 'homes#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end


  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'searchs#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #ファロー・フォロワー機能のアソシエーション
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  #ここまで
  #ファロー・フォロワー機能のメソッド
  def follow(user_id)
    unless self.id == user_id.to_i
      self.relationships.create(followed_id: user_id) #self = current_userだけに限定しないため・書く必要はないが書かない場合も実際は隠れている
    end
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  #ここまで


  attachment :profile_image

  validates :name, length: {minimum: 2, maximum: 20 }, uniqueness: true

  validates :introduction, length: {maximum: 50 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = @book.user
    if @book.save
      redirect_to book_path(@book.id)
      flash[:success] = "You have created book successfully."
    else
      @books = Book.all
      flash.now[:danger] = "新規投稿に失敗しました"
      render :index
    end
  end

  def index
    # @book = Book.find(params[:id])
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:success] = "You have updated book successfully."
    else
      flash.now[:danger] = "errors prohibited this obj from being saved:"
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to  books_path
    else
      @book.destroy
      redirect_to books_path
    end

  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_to request.referer 非同期通信を行うため削除
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to request.referer 非同期通信を行うため削除
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    #viewのform_tagにて
    #選択したmodelの値を@modelに代入。
    @model = params["model"]
    #選択した検索方法の値を@methodに代入。
    @method = params["method"]
    #検索ワードを@contentを代入。
    @content =params["content"]
    #@model, @content, @methodを代入した。
    #search_forを@recordsに代入。
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    #選択したモデルがuserだったら
    if model == 'User'
      #選択した検索方法が完全一致だったら
      if method =='perfect'
        User.where(name: content)
      #選択した検索方法が部分一致だったら
      else
        User.where('name LIKE ?', '%'+content+'%') #LIKEは曖昧な際に使える
      end
    #選択したモデルがBookだったら
    elsif model == 'Book'
      if method == 'perfect'
        Book.where(title: content)
      else
        Book.where('title LIKE ?', '%'+content+"%")
      end
    end
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    #viewのform_tagにて
    #選択したmodelの値を@modelに代入。
    @model = params["model"]
    #選択した検索方法の値を@methodに代入。
    @method = params["method"]
    #検索ワードを@contentを代入。
    @content =params["content"]
    #@model, @content, @methodを代入した。
    #search_forを@recordsに代入。
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    #選択したモデルがuserだったら
    if model == 'user'
      #選択した検索方法が完全一致だったら
      if method =='perfect'
        User.where(name: content)
      #選択した検索方法が部分一致だったら
      else
        User.where('name LIKE ?', '%'+content+'%') #LIKEは曖昧な際に使える
      end
    #選択したモデルがBookだったら
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      else
        Book.where('title LIKE ?', '%'+content+"%")
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def index
    @book = Book.new
   
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:success] = "You have updated user successfully."
    else
      flash[:danger] = "プロフィールの更新に失敗しました"
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scal

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: 'navbar-brand p-3' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to "Home", user_path(current_user), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li>
              <%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li>
              <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            <li class="nav-item">
            <% else %>
              <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <main>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <% if user_signed_in? %>
              <%= form_with url:search_path, method: :get do |f| %>
                <%= f.text_field :content %>
                <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
                <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }) %>
                <%= f.submit '検索' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>